lsi: false
safe: true
source: [https://github.com/KwKKei/DSC180AB-StaticWebsite]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima
title: Privacy Verb 
description: Barebones static site for Privacy Verb